version: "3"
services:
  mailing-service:
    image: maildev/maildev
    container_name: mailing-ser-0
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      - app-network
    restart: unless-stopped
  storage-service:
    image: postgres
    container_name: postgres_container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: yassine
      POSTGRES_DB: draft
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    networks:
      - app-network
    restart: unless-stopped
  app_api:
    container_name: back_side
    image: security_system1.0.3:latest
    ports:
      - 8088:8088
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - storage-service
  app-front:
    image: security_system_front:latest
    container_name: front_app
    ports:
      - 8080:80
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - app_api
volumes:
  postgres:

networks:
  app-network:
    driver: bridge