/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { activateAccount } from '../fn/auth/activate-account';
import { ActivateAccount$Params } from '../fn/auth/activate-account';
import { authenticate } from '../fn/auth/authenticate';
import { Authenticate$Params } from '../fn/auth/authenticate';
import { AuthenticationResponse } from '../models/authentication-response';
import { checkRecovery } from '../fn/auth/check-recovery';
import { CheckRecovery$Params } from '../fn/auth/check-recovery';
import { demandRecovery } from '../fn/auth/demand-recovery';
import { DemandRecovery$Params } from '../fn/auth/demand-recovery';
import { register } from '../fn/auth/register';
import { Register$Params } from '../fn/auth/register';
import { setNewPassword } from '../fn/auth/set-new-password';
import { SetNewPassword$Params } from '../fn/auth/set-new-password';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `register()` */
  static readonly RegisterPath = '/auth/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `register()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register$Response(params: Register$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return register(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `register$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register(params: Register$Params, context?: HttpContext): Observable<{
}> {
    return this.register$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `demandRecovery()` */
  static readonly DemandRecoveryPath = '/auth/demand-recovery';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `demandRecovery()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  demandRecovery$Response(params: DemandRecovery$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return demandRecovery(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `demandRecovery$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  demandRecovery(params: DemandRecovery$Params, context?: HttpContext): Observable<{
}> {
    return this.demandRecovery$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `authenticate()` */
  static readonly AuthenticatePath = '/auth/authenticate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authenticate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authenticate$Response(params: Authenticate$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResponse>> {
    return authenticate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authenticate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authenticate(params: Authenticate$Params, context?: HttpContext): Observable<AuthenticationResponse> {
    return this.authenticate$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthenticationResponse>): AuthenticationResponse => r.body)
    );
  }

  /** Path part for operation `setNewPassword()` */
  static readonly SetNewPasswordPath = '/auth/set-new-password';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setNewPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setNewPassword$Response(params: SetNewPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return setNewPassword(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setNewPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setNewPassword(params: SetNewPassword$Params, context?: HttpContext): Observable<{
}> {
    return this.setNewPassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `checkRecovery()` */
  static readonly CheckRecoveryPath = '/auth/check-recovery';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkRecovery()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkRecovery$Response(params: CheckRecovery$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return checkRecovery(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkRecovery$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkRecovery(params: CheckRecovery$Params, context?: HttpContext): Observable<{
}> {
    return this.checkRecovery$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `activateAccount()` */
  static readonly ActivateAccountPath = '/auth/activate-account';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `activateAccount()` instead.
   *
   * This method doesn't expect any request body.
   */
  activateAccount$Response(params: ActivateAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return activateAccount(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `activateAccount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  activateAccount(params: ActivateAccount$Params, context?: HttpContext): Observable<{
}> {
    return this.activateAccount$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
