spring:
  datasource:
    username: yassine
    password: password
    url: jdbc:postgresql://localhost:5432/draft
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: draftname53@gmail.com
    password: iutj idzb cfmp khtb
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enabled: true
    protocol: smtp



