/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CarResponse {
  car?: string;
  description?: string;
  ownerFullName?: string;
  prodYear?: number;
}
